export const NOSOTROS_STYLES = {
    section: "py-24 bg-[#0a0a0a] relative overflow-hidden",
    container: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8",
    header: "text-center mb-16",
    label: "text-ced-accent font-black tracking-[0.3em] uppercase text-xs opacity-80",
    title: "text-3xl md:text-5xl font-bold text-white mb-4",
    divider: "w-24 h-1 bg-ced-accent mx-auto",
    subtitle: "mt-4 text-xl text-gray-400",
    grid: "grid grid-cols-1 md:grid-cols-2 gap-12 items-center",
    image: "rounded-xl shadow-2xl w-full h-[400px] object-cover",
    cards_wrap: "order-1 md:order-2 space-y-6",
    card: "bg-[#1e1e1e] p-6 rounded-xl border-l-4 border-ced-accent transition-all hover:bg-[#2a2a2a]",
    card_title: "text-xl font-bold text-white mb-2",
    card_desc: "text-gray-400 text-sm leading-relaxed",
    audience_section: "py-24 bg-ced-blue text-white relative",
    audience_header: "text-center mb-16",
    audience_title: "text-3xl md:text-5xl font-bold mb-4",
    audience_desc: "text-blue-100 max-w-2xl mx-auto text-lg opacity-80",
    audience_grid: "grid grid-cols-1 md:grid-cols-3 gap-8",
    audience_card: "bg-black/20 backdrop-blur-md p-8 rounded-2xl border border-white/10 text-center hover:bg-black/30 transition-all",
    audience_icon_wrap: "w-20 h-20 bg-ced-accent rounded-full flex items-center justify-center mx-auto mb-6 text-white text-3xl shadow-xl",
    audience_title_main: "text-xl font-bold mb-3",
    audience_text: "text-blue-50 text-sm leading-relaxed opacity-70"
};
