export const HOME_STYLES = {
    navbar: {
        nav: (scrolled: boolean) => `fixed w-full z-50 top-0 transition-all duration-300 ${scrolled ? 'bg-ced-gray shadow-2xl py-2' : 'bg-transparent py-4'}`,
        container: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8",
        inner: "flex justify-between h-16 items-center",
        logo_wrap: "flex items-center gap-3 group cursor-pointer",
        logo_icon: "w-10 h-10 bg-ced-blue rounded-xl flex items-center justify-center font-bold text-white text-xl shadow-lg ring-4 ring-ced-blue/20 group-hover:rotate-12 transition-all",
        logo_text_wrap: "flex flex-col leading-none",
        logo_name: "font-black tracking-tighter text-white text-xl uppercase",
        logo_sub: "text-[10px] text-ced-accent font-bold tracking-[0.2em] uppercase",
        desktop_nav: "hidden md:flex space-x-10 items-center",
        link: "text-white/70 hover:text-white font-bold text-sm uppercase tracking-widest transition-colors relative group",
        link_accent: "absolute -bottom-1 left-0 w-0 h-0.5 bg-ced-accent transition-all group-hover:w-full",
        cta: "bg-ced-blue text-white px-7 py-3 rounded-full font-black text-xs uppercase tracking-widest hover:bg-ced-light transition-all transform hover:scale-105 shadow-xl shadow-ced-blue/30 flex items-center gap-2 ring-1 ring-white/20",
        mobile_btn: "md:hidden text-white cursor-pointer",
        mobile_menu: (isOpen: boolean) => `md:hidden absolute w-full bg-ced-gray border-t border-white/5 transition-all duration-300 ${isOpen ? 'opacity-100 visible h-auto py-8' : 'opacity-0 invisible h-0'}`,
        mobile_inner: "px-6 space-y-4",
        mobile_link: "block text-white font-bold text-lg uppercase tracking-widest py-2",
        mobile_cta: "w-full bg-ced-blue text-white py-4 rounded-xl font-black uppercase tracking-widest text-sm"
    },
    hero: {
        section: "relative pt-40 pb-20 md:pt-56 md:pb-40 flex items-center min-h-screen bg-ced-gray overflow-hidden",
        bg_overlay: "absolute inset-0 pointer-events-none overflow-hidden",
        bg_circle1: "absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-ced-blue/20 blur-[120px] rounded-full animate-pulse",
        bg_circle2: "absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-ced-accent/10 blur-[120px] rounded-full animate-delay-1000",
        container: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 w-full",
        grid: "grid grid-cols-1 lg:grid-cols-2 gap-16 items-center",
        content_wrap: "space-y-10",
        badge: "inline-flex items-center gap-2 px-5 py-2.5 rounded-full bg-white/5 border border-white/10 text-ced-accent text-xs font-black uppercase tracking-[0.2em] shadow-inner",
        badge_dot: "flex h-2 w-2 rounded-full bg-ced-accent animate-ping",
        title: "text-6xl md:text-[5.5rem] font-black text-white leading-[0.95] tracking-tighter",
        title_accent: "text-transparent bg-clip-text bg-gradient-to-r from-ced-accent to-blue-400",
        desc: "text-xl text-slate-400 max-w-xl leading-relaxed font-medium",
        btn_row: "flex flex-col sm:flex-row gap-6 pt-4",
        btn_primary: "px-12 py-6 bg-ced-blue text-white font-black rounded-2xl shadow-[0_20px_50px_rgba(30,58,138,0.4)] hover:bg-ced-light transition-all transform hover:-translate-y-2 text-center uppercase tracking-widest text-sm flex items-center justify-center gap-3 group",
        btn_secondary: "px-12 py-6 bg-white/5 text-white border border-white/10 font-black rounded-2xl hover:bg-white/10 transition-all transform hover:-translate-y-1 text-center uppercase tracking-widest text-sm",
        img_container: "relative lg:block hidden",
        img_wrap: "relative z-10 rounded-[2.5rem] overflow-hidden border-8 border-white/5 shadow-2xl skew-y-1 hover:skew-y-0 transition-all duration-700 bg-slate-800",
        img: "object-cover opacity-90 grayscale-[20%] hover:grayscale-0 transition-all duration-700",
        img_fade: "absolute inset-0 bg-gradient-to-t from-ced-gray via-transparent to-transparent opacity-60"
    },
};
