export const CONTACTO_STYLES = {
    section: "py-32 bg-[#0f172a] relative overflow-hidden",
    container: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10",
    header: "text-center mb-20",
    title: "text-5xl md:text-7xl font-black text-white mb-6 uppercase tracking-tighter",
    subtitle: "text-xl text-ced-accent font-bold uppercase tracking-[0.2em] opacity-80",
    grid: "grid grid-cols-1 lg:grid-cols-2 gap-12 items-stretch",
    
    info_card: "bg-white/5 backdrop-blur-xl p-12 rounded-[32px] border border-white/10 shadow-2xl flex flex-col justify-between",
    info_title: "text-3xl font-black text-white mb-10 uppercase tracking-tight",
    info_items: "space-y-8",
    icon_circle: "w-14 h-14 bg-ced-blue/20 rounded-2xl flex items-center justify-center mr-6 shadow-inner ring-1 ring-white/10 group-hover:bg-ced-blue transition-all duration-300",
    icon_svg: "w-6 h-6 text-ced-accent group-hover:text-white transition-colors",
    label: "text-[10px] font-bold uppercase tracking-widest text-ced-accent mb-1",
    value: "text-lg text-white font-semibold tracking-tight",
    
    why_card: "bg-ced-blue p-12 rounded-[32px] shadow-[0_0_50px_rgba(30,58,138,0.3)] text-white flex flex-col justify-center relative overflow-hidden",
    why_title: "text-3xl font-black mb-8 uppercase tracking-tight",
    why_list: "space-y-6",
    check_icon: "w-6 h-6 text-ced-accent mr-4 flex-shrink-0 group-hover:scale-125 transition-transform",
    check_item: "flex items-center text-xl font-bold tracking-tight group cursor-default",
    
    glow: "absolute -top-24 -right-24 w-96 h-96 bg-ced-accent/10 blur-[120px] rounded-full",

    form_col: "bg-[#0a0a0a] p-10 rounded-2xl shadow-xl",
    form: "space-y-6",
    field_group: "space-y-2",
    field_label: "block text-sm font-medium text-gray-300",
    input: "w-full bg-[#1e293b] border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-ced-accent transition-colors",
    textarea: "w-full bg-[#1e293b] border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-ced-accent transition-colors resize-none h-32",
    submit_btn: "w-full bg-ced-accent hover:bg-sky-500 text-white font-bold py-4 rounded-lg transition-colors flex items-center justify-center group",
    btn_text: "mr-2",
    btn_icon_wrap: "transform group-hover:translate-x-1 transition-transform",
    btn_icon: "w-5 h-5",
    form_footer: "text-center text-gray-500 text-xs mt-4",
    info_col: "space-y-12",
    info_list: "space-y-8",
    info_item: "flex items-start group",
    info_label: "text-xl font-bold text-white mb-2",
    info_value: "text-gray-400 font-medium",
    icon_wrap: (color: string) => `w-14 h-14 rounded-full flex items-center justify-center mr-6 transition-colors duration-300 ${color}`
};
