export const FOOTER_STYLES = {
    footer: "bg-ced-blue text-white pt-20 pb-10",
    container: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8",
    grid: "grid grid-cols-1 md:grid-cols-4 gap-12 mb-16",
    brand_col: "col-span-1 md:col-span-2",
    brand_name: "font-black text-3xl tracking-tighter block mb-6 uppercase",
    brand_accent: "text-ced-accent",
    brand_desc: "text-blue-100/60 max-w-sm leading-relaxed",
    col_title: "font-bold text-xl mb-6",
    link_list: "space-y-3 text-blue-100/60",
    link_item: "hover:text-white transition-colors cursor-pointer font-medium",
    bottom: "border-t border-white/10 pt-10 text-center text-blue-100/50 font-bold text-xs uppercase tracking-widest",
    newsletter_wrap: "col-span-1 md:col-span-4 flex flex-col items-center justify-center text-center mt-8",
    newsletter_title: "font-bold text-xl mb-6 text-center",
    input_group: "flex flex-col gap-3 w-full max-w-md mx-auto",
    input: "bg-white/10 border border-white/20 rounded-full px-6 py-4 text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-ced-accent/50 transition-all font-medium text-sm text-center",
    btn: "bg-ced-accent text-white font-black rounded-full py-4 tracking-widest uppercase text-[10px] hover:bg-white hover:text-ced-blue transition-all shadow-lg active:scale-95 w-full",
    img_fade: "hidden",
    img: "max-w-[280px] md:max-w-[340px] h-auto block transform transition duration-700 group-hover:scale-105 relative z-10",
};
